config/routes.rb
Rails.application.routes.draw do
  root "games#index"

  concern :player do
    member do
      get "getting_started"
      get "play"
      get "end"
    end
  end

  concern :seller_api do
    collection do
      post "market_setup"
    end
  end

  concern :buyer_api do
    collection do
      post "purchase"
    end
  end

  concern :game_api do
    collection do
      post "wait"
    end
  end

  resources :games, shallow: true do
    member do
      post "join"
    end

    resources :buyers, concerns: :player
    resources :sellers, concerns: :player
  end

  scope :api do
    defaults format: :json do
      resources :sellers, concerns: :seller_api
      resources :buyers, concerns: :buyer_api
      resources :games, concerns: :game_api
    end
  end

  namespace :admin do
    resources :games do
      member do
        post "refresh"
        get "results", defaults: {format: "csv"}
      end
    end
    resources :players
    resources :settings
  end

  resources :admin

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/admin/_nav-item.html.erb
<li class="pure-menu-item">
  <%= nav_item_link(local_assigns[:name], local_assigns[:path]) %>
</li>

app/views/admin/_nav.html.erb
<div class="nav pure-u">
  <div class="nav-inner">
    <div class="pure-menu">
      <ul class="pure-menu-list">
        <%= render "admin/nav-item", name: 'Home 🏡', path: admin_index_path %>

        <%= render "admin/nav-item", name: 'Games 🎲', path: admin_games_path %>

        <%= render "admin/nav-item", name: 'Settings 🛠️', path: admin_settings_path %>
      </ul>
    </div>
  </div>
</div>

app/views/admin/index.html.erb
<h1>Administration Section</h1>

<div class="container mt-3">
  <div class="row">
    <div class="col">
      <div>
        <p>This page has no specific goal but to say hello ❤️ 👋.</p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div>
        <p>There has been a total of <b><%= @games.count %> games played</b> here.</p>
        <p>There are currently <b><%= @games.with_ongoing_state.count %> games being played</b> right now.</p>
        <p>
          To see the list of games or <b>create your own game</b> take a look at the menu or
          <%= link_to 'Click here', admin_games_path %>
        </p>
      </div>
    </div>
  </div>
</div>

<% content_for :debug do %>
  <p>Find me in <%= __FILE__ %></p>
<% end %>