config/routes.rb
Rails.application.routes.draw do
  root "games#index"

  concern :player do
    member do
      get "getting_started"
      get "play"
      get "end"
    end
  end

  concern :seller_api do
    collection do
      post "market_setup"
    end
  end

  concern :buyer_api do
    collection do
      post "purchase"
    end
  end

  concern :game_api do
    collection do
      post "wait"
    end
  end

  resources :games, shallow: true do
    member do
      post "join"
    end

    resources :buyers, concerns: :player
    resources :sellers, concerns: :player
  end

  scope :api do
    defaults format: :json do
      resources :sellers, concerns: :seller_api
      resources :buyers, concerns: :buyer_api
      resources :games, concerns: :game_api
    end
  end

  namespace :admin do
    resources :games do
      member do
        post "refresh"
        get "results", defaults: {format: "csv"}
      end
    end
    resources :players
    resources :settings
  end

  resources :admin

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/game.rb
require "workflow"
require "workflow_activerecord"

class Game < ApplicationRecord
  has_many :sellers, -> { order(:created_at) }, inverse_of: :game, dependent: :destroy
  has_many :buyers, -> { order(:created_at) }, inverse_of: :game, dependent: :destroy
  has_many :rounds, dependent: :destroy
  has_one :current_round, -> { merge(Round.current) }, class_name: "Round"

  include WorkflowActiverecord

  workflow do
    state :new do
      event :start, transitions_to: :ongoing, if: :ready_to_start?
    end
    state :ongoing do
      event :new_round, transitions_to: :ongoing, if: proc { |g| !g.last_round? }
      event :new_round, transitions_to: :finished, if: :last_round?
      event :force_stop, transitions_to: :finished
    end
    state :finished
    state :removed

    on_transition do |from, to, event, *event_args|
      broadcast_status(to)
    end
  end

  default_scope do
    where.not(remove_state)
  end

  scope :order_by_state, ->(dir = :asc) do
    direction = Arel.sql(dir.downcase.to_s == "desc" ? "DESC" : "ASC")
    order(
      states.map { |state|
        "workflow_state = '#{state}' #{direction}"
      }.join(", ")
    )
  end

  # Get the current controller action on which clients should be connected
  # depending on the current_state (workflow_state)
  def current_action
    self.class.state_to_controller_action(workflow_state)
  end

  def current_round_number
    current_round.number
  end

  def start
    collect_players_bret_results!

    new_round
  end

  def new_round
    # End existing current round
    current_round&.stop!

    # Create a new round
    unless last_round?
      sellers.map(&:play!) && buyers.map(&:play!)
      rounds.create(number: rounds.count + 1)
    end
  end

  def remove!
    update_columns(self.class.remove_state)
  end

  def to_s
    "#<Game:#{id} state=#{workflow_state} #buyers=#{buyers.count} #sellers=#{sellers.count}>"
  end

  def public_url
    Rails.application.routes.url_helpers.game_path(id)
  end

  def players
    {buyers: buyers, sellers: sellers}
  end

  def are_all_players_waiting?
    sellers.all?(&:waiting?) && buyers.all?(&:waiting?)
  end

  def ready_to_start?
    players.values.map(&:count).all?(&:positive?)
  end

  def first_round?
    nth_round?(1)
  end

  def last_round?
    nth_round?(Setting.find_by_key(Setting::CONFIGURABLE_ROUNDS_COUNT))
  end

  def valid_market_setup!
    broadcast_status if market_setup_finished?
  end

  def market_setup_finished?
    sellers.all? do |seller|
      seller.current_round_products.present?
    end
  end

  def valid_market_closing!
    broadcast_status if market_closed?
  end

  def market_closed?
    buyers.all? do |buyer|
      buyer.current_round_transactions.present?
    end
  end

  def broadcast_status(to_state = nil)
    players.values.flatten.each do |player|
      send_status(player, to_state)
    end
  end

  def send_status(player, to_state = nil)
    GameChannel.broadcast_to(
      player,
      serializable_hash(
        to_state: to_state,
        player: player,
        mine: player.id
      )
    )
  end

  def serializable_hash(params)
    serializer(params).serializable_hash
  end

  def serializable_json(params)
    serializer(params).serializable_json
  end

  def to_live
    Hash[players.map { |k, v| [k, v.count] }]
      .merge(current_state: workflow_state)
  end

  private

  def collect_players_bret_results!
    [buyers, sellers].map do |players|
      players.each(&:fetch_bret_results!)
    end
  end

  def nth_round?(n)
    current_round &&
      current_round.number >= n
  end

  def serializer(params)
    GameSerializer.new(
      self,
      {
        params: params,
        include: [:sellers, :'sellers.products', :current_round, :me],
      }
    )
  end

  class << self
    def remove_state
      {workflow_state: :removed}
    end

    def states
      Game.workflow_spec.states.keys
    end

    def state_to_controller_action(workflow_state)
      case workflow_state
      when "new"
        "getting_started"
      when "ongoing"
        "play"
      when "finished"
        "end"
      end
    end
  end
end

app/controllers/admin/games_controller.rb
module Admin
  class GamesController < AdminController
    include AdminHelper

    def index
      @games = Game.all
      @order = order_params[:order]

      if @order
        @games = if @order[:workflow_state]
          @games.order_by_state(@order[:workflow_state])
        else
          @games.order(@order.to_h)
        end
      end
    rescue ArgumentError
    end

    def new
    end

    def show
      current_game
    end

    def refresh
      current_game.broadcast_status
      redirect_to request.referer || admin_games_path
    end

    def results
      player_type = params.require(:type).to_s.downcase
      unless [Buyer, Seller].map(&:to_s).map(&:downcase).include?(player_type)
        raise "Only 'buyer's or 'seller's results type can be retrieved (passed #{player_type})"
      end

      respond_to do |format|
        format.csv do
          sql_query = "SELECT * FROM #{player_type}s_reporting_view WHERE game = '#{current_game.name}'"
          filename = [
            ActiveSupport::Inflector.transliterate(current_game.name.downcase.gsub(/\s/, "_")),
            player_type,
            "results",
          ].join(".")
          rows = []

          stream_query_rows(sql_query) do |row|
            rows << row
          end

          render csv: rows.join(""), filename: filename
        end
      end
    end

    def create
      @game = Game.new(game_params)

      # <wake-up Heroku>
      BretHelper::Bret.new.fetch(BretHelper::Bret::BRET_DEMO_HOST)
      # </wake-up Heroku>

      @game.save
      flash[:info] = <<~INFO
        Your game has been created!
        You can now share the public url #{random_earth}
        #{request.protocol}#{request.host}:#{request.port}#{@game.public_url}
      INFO
      redirect_to admin_game_path(@game)
    end

    def update
      @game = current_game

      command = update_game_params

      if command.present?
        case command[:event]
        when "start"
          @game.start!
        when "stop"
          @game.force_stop!
        when "round"
          @game.new_round!
        end
      end
    rescue Workflow::NoTransitionAllowed
      flash[:error] = "You can't #{command[:event]} this game. Are there any players yet?"
    ensure
      respond_to do |format|
        format.html { redirect_to admin_game_url(@game) }
        format.json { render json: @game }
      end
    end

    def destroy
      @game = current_game

      @game.remove!
      flash[:alert] = "Your game has been removed."

      redirect_to admin_games_path
    end

    private

    def stream_query_rows(sql_query, options = "WITH CSV HEADER")
      conn = ActiveRecord::Base.connection.raw_connection
      conn.copy_data "COPY (#{sql_query}) TO STDOUT #{options}" do
        while (row = conn.get_copy_data)
          yield row
        end
      end
    end

    def current_game
      @game = Game.find(params[:id])
    end

    def game_params
      params.require(:game).permit(:name)
    end

    def update_game_params
      params.require(:game).permit(:event)
    end

    def order_params
      params.permit(order: [:created_at, :name, :workflow_state])
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  include GameApiConcern

  def index
    @games = Game.with_new_state
  end

  def join
    new_game!
    player_type = case join_commit_params
                  when Seller.to_s
                    @game.sellers
                  when Buyer.to_s
                    @game.buyers
    end
    bret = BretHelper::Bret.new
    bret_urls = {
      bret_session: bret.session_uri,
      bret_admin: bret.admin_uri,
    }
    @player = player_type.create(
      bret_urls.merge(join_player_params[:player] || {})
    )

    if @player.save
      persist_player_cookie(@player)
      redirect_to @player.url_path
    else
      flash[:error] = @player.errors.full_messages
      render status: :bad_request, action: :show
    end
  end

  def show
    new_game!
  end

  private

  def one_params
    params.require(:id)
  end

  def join_commit_params
    params.require(:commit)
  end

  def join_player_params
    params.require(:game).permit(player: [:name, :age, :sex, :profession])
  end

  def new_game!
    @game = Game.with_new_state.find(one_params)
  end
end

app/views/admin/games/index.html.erb
<h1>List of games</h1>

<div class="container mt-3">
  <div class="row">
    <div class="col">
      <div>
        <p>The following table lists all games played on this website.</p>
      </div>
    </div>
  </div>
</div>

<div class="container mt-3">
  <div class="row">
    <% if @games.present? %>
      <table class="pure-table pure-table-striped pure-table-horizontal">
        <thead>
          <tr>
            <th>Name
              <%= order_link(:name, order: @order) %>
            </th>
            <th>State
              <%= order_link(:workflow_state, order: @order) %>
            </th>
            <th>Created at
              <%= order_link(:created_at, order: @order) %>
            </th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @games.each do |game| %>
            <tr>
              <td><%= link_to game.name.blank? ? 'Unnamed game' : game.name, admin_game_url(game) %></td>
              <td><%= game.workflow_state %></td>
              <td><%= game.created_at %></td>
              <td>
                <%= render_game_actions(game) %>
              </td>
            </tr>
        </tbody>
      <% end %>
      </table>
    <% else %>
      <b>No games found!</b>
    <% end %>
  </div>
</div>

<div class="container mt-3">
  <div class="row">
    <%= link_to '➕ Create a new game',
                new_admin_game_path,
                class: 'btn pure-button' %>
  </div>
</div>

<% content_for :debug do %>
  <p>Find me in <%= __FILE__ %></p>
<% end %>

app/views/admin/games/new.html.erb
<h1>Admin - Games#new</h1>

<div class="container mt-3">
  <div class="row">
    <%= form_with url: admin_games_path, scope: :game, local: true do |form| %>
      <p>
        <%= form.label :name %><br>
        <%= form.text_field :name %>
      </p>

      <p>
        <%= form.submit nil, class: 'pure-button pure-button-primary btn' %>
        <%= link_to 'Back', admin_games_path, class: 'pure-button btn' %>
      </p>
    <% end %>
  </div>
</div>


<% content_for :debug do %>
  <p>Find me in <%= __FILE__ %></p>
<% end %>

app/views/admin/games/show.html.erb
<div class="container">
  <div class="row mb-3">
    <div class="col">
      <h1>Administration page <small class="text-muted">(don't share link publicly)</small></h1>
    </div>
  </div>
</div>

<div class="container">
  <div class="row mb-3">
    <div class="col">
      <h3>Game details</h3>
      <table class="pure-table pure-table-striped pure-table-horizontal">
        <thead>
          <tr>
            <th><em>Name</em></th>
            <th><em>State</em></th>
            <th><em>Round</em></th>
            <th><em>Actions</em></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @game.name %></td>
            <td><%= @game.workflow_state %></td>
            <td><%= @game&.current_round&.number %>/<%= Setting.find_by_key(Setting::CONFIGURABLE_ROUNDS_COUNT) %></td>
            <td><%= render_game_actions(@game) %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <h3>Buyers
        <% if @game.finished? %>
          <small>
            <%= link_to(results_admin_game_url(id: @game.id, type: Buyer),
                        title: "Download buyers results as CSV",
                        class: "text-muted",
                        target: "_blank") { "🖇️  results " }
            %>
          </small>
        <% end %>
      </h3>
      <table class="pure-table pure-table-striped pure-table-horizontal">
        <thead>
          <tr>
            <th><em>Name</em></th>
            <th><em>State</em></th>
            <th><em>Money</em></th>
            <th><em>Utility</em></th>
            <th><em>Bret</em></th>
            <th><em>Actions</em></th>
          </tr>
        </thead>
        <tbody>
          <% @game.buyers.each do |buyer| %>
            <tr>
              <td><%= buyer.name %></td>
              <td>
                <%= buyer.workflow_state %>
                <small class="<%= buyer.online? ? 'text-success' : 'text-danger' %>">
                  (<%= buyer.online? ? 'online' : 'offline' %>)
                </small>
              </td>
              <td><%= buyer.money %></td>
              <td><%= buyer.utility %></td>
              <td>
                <% if buyer.bret_boxes_collected %>
                  <span class="text-<%= ['0.00','0'].include?(buyer.bret_payoff) ? 'danger' : 'success' %>">
                    <%= buyer.bret_boxes_collected %>/100
                  </span>
                <% end %>
              </td>
              <td>
                <%= render_player_actions(buyer) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col">
      <h3>Sellers
        <% if @game.finished? %>
          <small>
            <%= link_to(results_admin_game_url(id: @game.id, type: Seller),
                        title: "Download sellers results as CSV",
                        class: "text-muted",
                        target: "_blank") { "🖇️  results " }
            %>
          </small>
        <% end %>
      </h3>
      <table class="pure-table pure-table-striped pure-table-horizontal">
        <thead>
          <tr>
            <th><em>Name</em></th>
            <th><em>State</em></th>
            <th><em>Certificate</em></th>
            <th><em>Money</em></th>
            <th><em>Profit</em></th>
            <th><em>Bret</em></th>
            <th><em>Actions</em></th>
          </tr>
        </thead>
        <tbody>
          <% @game.sellers.each do |seller| %>
            <tr>
              <td><%= seller.name %></td>
              <td>
                <%= seller.workflow_state %>
                <small class="<%= seller.online? ? 'text-success' : 'text-danger' %>">
                  (<%= seller.online? ? 'online' : 'offline' %>)
                </small>
              </td>
              <td><%= '⭐' * (seller.certificate || 0) %></td>
              <td><%= seller.money %></td>
              <td><%= seller.profit %></td>
              <td>
                <% if seller.bret_boxes_collected %>
                  <span class="text-<%= ['0.00','0'].include?(seller.bret_payoff) ? 'danger' : 'success' %>">
                    <%= seller.bret_boxes_collected %>/100
                  </span>
                <% end %>
              </td>
              <td>
                <%= render_player_actions(seller) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<% content_for :debug do %>
  <p>Find me in <%= __FILE__ %></p>
  <p><%= @game %></p>
<% end %>